// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.0--rc2
// source: wal/proto/wal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Null          bool                   `protobuf:"varint,1,opt,name=null,proto3" json:"null,omitempty"`
	Type          uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	BoolVal       bool                   `protobuf:"varint,3,opt,name=bool_val,json=boolVal,proto3" json:"bool_val,omitempty"`
	Int32Val      int32                  `protobuf:"varint,4,opt,name=int32_val,json=int32Val,proto3" json:"int32_val,omitempty"`
	Uint32Val     uint32                 `protobuf:"varint,5,opt,name=uint32_val,json=uint32Val,proto3" json:"uint32_val,omitempty"`
	Int64Val      int64                  `protobuf:"varint,6,opt,name=int64_val,json=int64Val,proto3" json:"int64_val,omitempty"`
	Uint64Val     uint64                 `protobuf:"varint,7,opt,name=uint64_val,json=uint64Val,proto3" json:"uint64_val,omitempty"`
	FloatVal      float32                `protobuf:"fixed32,8,opt,name=float_val,json=floatVal,proto3" json:"float_val,omitempty"`
	DoubleVal     float64                `protobuf:"fixed64,9,opt,name=double_val,json=doubleVal,proto3" json:"double_val,omitempty"`
	StringVal     string                 `protobuf:"bytes,10,opt,name=string_val,json=stringVal,proto3" json:"string_val,omitempty"`
	BinaryVal     []byte                 `protobuf:"bytes,11,opt,name=binary_val,json=binaryVal,proto3" json:"binary_val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_wal_proto_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_wal_proto_wal_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetNull() bool {
	if x != nil {
		return x.Null
	}
	return false
}

func (x *Value) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Value) GetBoolVal() bool {
	if x != nil {
		return x.BoolVal
	}
	return false
}

func (x *Value) GetInt32Val() int32 {
	if x != nil {
		return x.Int32Val
	}
	return 0
}

func (x *Value) GetUint32Val() uint32 {
	if x != nil {
		return x.Uint32Val
	}
	return 0
}

func (x *Value) GetInt64Val() int64 {
	if x != nil {
		return x.Int64Val
	}
	return 0
}

func (x *Value) GetUint64Val() uint64 {
	if x != nil {
		return x.Uint64Val
	}
	return 0
}

func (x *Value) GetFloatVal() float32 {
	if x != nil {
		return x.FloatVal
	}
	return 0
}

func (x *Value) GetDoubleVal() float64 {
	if x != nil {
		return x.DoubleVal
	}
	return 0
}

func (x *Value) GetStringVal() string {
	if x != nil {
		return x.StringVal
	}
	return ""
}

func (x *Value) GetBinaryVal() []byte {
	if x != nil {
		return x.BinaryVal
	}
	return nil
}

type VectorValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Float32S      []float32              `protobuf:"fixed32,1,rep,packed,name=float32s,proto3" json:"float32s,omitempty"`
	Float64S      []float64              `protobuf:"fixed64,2,rep,packed,name=float64s,proto3" json:"float64s,omitempty"`
	Int8S         []int32                `protobuf:"varint,3,rep,packed,name=int8s,proto3" json:"int8s,omitempty"`
	Int16S        []int32                `protobuf:"varint,4,rep,packed,name=int16s,proto3" json:"int16s,omitempty"`
	Int32S        []int32                `protobuf:"varint,5,rep,packed,name=int32s,proto3" json:"int32s,omitempty"`
	Int4S         []int32                `protobuf:"varint,6,rep,packed,name=int4s,proto3" json:"int4s,omitempty"`
	Float16S      []uint32               `protobuf:"varint,7,rep,packed,name=float16s,proto3" json:"float16s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorValue) Reset() {
	*x = VectorValue{}
	mi := &file_wal_proto_wal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorValue) ProtoMessage() {}

func (x *VectorValue) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_wal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorValue.ProtoReflect.Descriptor instead.
func (*VectorValue) Descriptor() ([]byte, []int) {
	return file_wal_proto_wal_proto_rawDescGZIP(), []int{1}
}

func (x *VectorValue) GetFloat32S() []float32 {
	if x != nil {
		return x.Float32S
	}
	return nil
}

func (x *VectorValue) GetFloat64S() []float64 {
	if x != nil {
		return x.Float64S
	}
	return nil
}

func (x *VectorValue) GetInt8S() []int32 {
	if x != nil {
		return x.Int8S
	}
	return nil
}

func (x *VectorValue) GetInt16S() []int32 {
	if x != nil {
		return x.Int16S
	}
	return nil
}

func (x *VectorValue) GetInt32S() []int32 {
	if x != nil {
		return x.Int32S
	}
	return nil
}

func (x *VectorValue) GetInt4S() []int32 {
	if x != nil {
		return x.Int4S
	}
	return nil
}

func (x *VectorValue) GetFloat16S() []uint32 {
	if x != nil {
		return x.Float16S
	}
	return nil
}

type SparseVectorValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indices       []uint32               `protobuf:"varint,1,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	Values        []float32              `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SparseVectorValue) Reset() {
	*x = SparseVectorValue{}
	mi := &file_wal_proto_wal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SparseVectorValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SparseVectorValue) ProtoMessage() {}

func (x *SparseVectorValue) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_wal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SparseVectorValue.ProtoReflect.Descriptor instead.
func (*SparseVectorValue) Descriptor() ([]byte, []int) {
	return file_wal_proto_wal_proto_rawDescGZIP(), []int{2}
}

func (x *SparseVectorValue) GetIndices() []uint32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *SparseVectorValue) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Doc struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Id            string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                       `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	DocId         uint64                        `protobuf:"varint,3,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Fields        map[string]*Value             `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Vectors       map[string]*VectorValue       `protobuf:"bytes,5,rep,name=vectors,proto3" json:"vectors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SparseVectors map[string]*SparseVectorValue `protobuf:"bytes,6,rep,name=sparse_vectors,json=sparseVectors,proto3" json:"sparse_vectors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Doc) Reset() {
	*x = Doc{}
	mi := &file_wal_proto_wal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Doc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doc) ProtoMessage() {}

func (x *Doc) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_wal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doc.ProtoReflect.Descriptor instead.
func (*Doc) Descriptor() ([]byte, []int) {
	return file_wal_proto_wal_proto_rawDescGZIP(), []int{3}
}

func (x *Doc) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Doc) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Doc) GetDocId() uint64 {
	if x != nil {
		return x.DocId
	}
	return 0
}

func (x *Doc) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Doc) GetVectors() map[string]*VectorValue {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *Doc) GetSparseVectors() map[string]*SparseVectorValue {
	if x != nil {
		return x.SparseVectors
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lsn           uint64                 `protobuf:"varint,1,opt,name=lsn,proto3" json:"lsn,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Doc           *Doc                   `protobuf:"bytes,4,opt,name=doc,proto3" json:"doc,omitempty"`
	Ids           []string               `protobuf:"bytes,5,rep,name=ids,proto3" json:"ids,omitempty"`
	Crc32         uint32                 `protobuf:"varint,6,opt,name=crc32,proto3" json:"crc32,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_wal_proto_wal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_wal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_wal_proto_wal_proto_rawDescGZIP(), []int{4}
}

func (x *LogEntry) GetLsn() uint64 {
	if x != nil {
		return x.Lsn
	}
	return 0
}

func (x *LogEntry) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *LogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogEntry) GetDoc() *Doc {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *LogEntry) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *LogEntry) GetCrc32() uint32 {
	if x != nil {
		return x.Crc32
	}
	return 0
}

var File_wal_proto_wal_proto protoreflect.FileDescriptor

const file_wal_proto_wal_proto_rawDesc = "" +
	"\n" +
	"\x13wal/proto/wal.proto\x12\x03wal\"\xbc\x02\n" +
	"\x05Value\x12\x12\n" +
	"\x04null\x18\x01 \x01(\bR\x04null\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x19\n" +
	"\bbool_val\x18\x03 \x01(\bR\aboolVal\x12\x1b\n" +
	"\tint32_val\x18\x04 \x01(\x05R\bint32Val\x12\x1d\n" +
	"\n" +
	"uint32_val\x18\x05 \x01(\rR\tuint32Val\x12\x1b\n" +
	"\tint64_val\x18\x06 \x01(\x03R\bint64Val\x12\x1d\n" +
	"\n" +
	"uint64_val\x18\a \x01(\x04R\tuint64Val\x12\x1b\n" +
	"\tfloat_val\x18\b \x01(\x02R\bfloatVal\x12\x1d\n" +
	"\n" +
	"double_val\x18\t \x01(\x01R\tdoubleVal\x12\x1d\n" +
	"\n" +
	"string_val\x18\n" +
	" \x01(\tR\tstringVal\x12\x1d\n" +
	"\n" +
	"binary_val\x18\v \x01(\fR\tbinaryVal\"\xbd\x01\n" +
	"\vVectorValue\x12\x1a\n" +
	"\bfloat32s\x18\x01 \x03(\x02R\bfloat32s\x12\x1a\n" +
	"\bfloat64s\x18\x02 \x03(\x01R\bfloat64s\x12\x14\n" +
	"\x05int8s\x18\x03 \x03(\x05R\x05int8s\x12\x16\n" +
	"\x06int16s\x18\x04 \x03(\x05R\x06int16s\x12\x16\n" +
	"\x06int32s\x18\x05 \x03(\x05R\x06int32s\x12\x14\n" +
	"\x05int4s\x18\x06 \x03(\x05R\x05int4s\x12\x1a\n" +
	"\bfloat16s\x18\a \x03(\rR\bfloat16s\"E\n" +
	"\x11SparseVectorValue\x12\x18\n" +
	"\aindices\x18\x01 \x03(\rR\aindices\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x02R\x06values\"\xd4\x03\n" +
	"\x03Doc\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x15\n" +
	"\x06doc_id\x18\x03 \x01(\x04R\x05docId\x12,\n" +
	"\x06fields\x18\x04 \x03(\v2\x14.wal.Doc.FieldsEntryR\x06fields\x12/\n" +
	"\avectors\x18\x05 \x03(\v2\x15.wal.Doc.VectorsEntryR\avectors\x12B\n" +
	"\x0esparse_vectors\x18\x06 \x03(\v2\x1b.wal.Doc.SparseVectorsEntryR\rsparseVectors\x1aE\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".wal.ValueR\x05value:\x028\x01\x1aL\n" +
	"\fVectorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.wal.VectorValueR\x05value:\x028\x01\x1aX\n" +
	"\x12SparseVectorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.wal.SparseVectorValueR\x05value:\x028\x01\"\x80\x01\n" +
	"\bLogEntry\x12\x10\n" +
	"\x03lsn\x18\x01 \x01(\x04R\x03lsn\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1a\n" +
	"\x03doc\x18\x04 \x01(\v2\b.wal.DocR\x03doc\x12\x10\n" +
	"\x03ids\x18\x05 \x03(\tR\x03ids\x12\x14\n" +
	"\x05crc32\x18\x06 \x01(\rR\x05crc32B)Z'github.com/third-apps/go-zvec/wal/protob\x06proto3"

var (
	file_wal_proto_wal_proto_rawDescOnce sync.Once
	file_wal_proto_wal_proto_rawDescData []byte
)

func file_wal_proto_wal_proto_rawDescGZIP() []byte {
	file_wal_proto_wal_proto_rawDescOnce.Do(func() {
		file_wal_proto_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wal_proto_wal_proto_rawDesc), len(file_wal_proto_wal_proto_rawDesc)))
	})
	return file_wal_proto_wal_proto_rawDescData
}

var file_wal_proto_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wal_proto_wal_proto_goTypes = []any{
	(*Value)(nil),             // 0: wal.Value
	(*VectorValue)(nil),       // 1: wal.VectorValue
	(*SparseVectorValue)(nil), // 2: wal.SparseVectorValue
	(*Doc)(nil),               // 3: wal.Doc
	(*LogEntry)(nil),          // 4: wal.LogEntry
	nil,                       // 5: wal.Doc.FieldsEntry
	nil,                       // 6: wal.Doc.VectorsEntry
	nil,                       // 7: wal.Doc.SparseVectorsEntry
}
var file_wal_proto_wal_proto_depIdxs = []int32{
	5, // 0: wal.Doc.fields:type_name -> wal.Doc.FieldsEntry
	6, // 1: wal.Doc.vectors:type_name -> wal.Doc.VectorsEntry
	7, // 2: wal.Doc.sparse_vectors:type_name -> wal.Doc.SparseVectorsEntry
	3, // 3: wal.LogEntry.doc:type_name -> wal.Doc
	0, // 4: wal.Doc.FieldsEntry.value:type_name -> wal.Value
	1, // 5: wal.Doc.VectorsEntry.value:type_name -> wal.VectorValue
	2, // 6: wal.Doc.SparseVectorsEntry.value:type_name -> wal.SparseVectorValue
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_wal_proto_wal_proto_init() }
func file_wal_proto_wal_proto_init() {
	if File_wal_proto_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wal_proto_wal_proto_rawDesc), len(file_wal_proto_wal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wal_proto_wal_proto_goTypes,
		DependencyIndexes: file_wal_proto_wal_proto_depIdxs,
		MessageInfos:      file_wal_proto_wal_proto_msgTypes,
	}.Build()
	File_wal_proto_wal_proto = out.File
	file_wal_proto_wal_proto_goTypes = nil
	file_wal_proto_wal_proto_depIdxs = nil
}
